zds_systems/users/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('processadd', views.processadd, name='processadd'),
    path('<int:user_id>/detail/', views.detail, name='detail'),
    ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

zds_systems/zds_systems/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

zds_systems/users/models.py
from django.db import models
from datetime import datetime
import os, random
from django.utils import timezone
from django.utils.html import mark_safe

# Timezone changed to Asia/Manila

now = timezone.now()

# User Image path (start)
# Update 6/27/2023 Asia/Manila

def image_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    _now = datetime.now()

    return 'profile_pic/{year}-{month}-{imageid}-{basename}-{randomstring}{ext}'.format(imageid = instance,
                                                                                         basename = basefilename, 
                                                                                         randomstring = randomstr, 
                                                                                         ext = file_extension, 
                                                                                         year = _now.strftime('%Y'), 
                                                                                         month = _now.strftime('%m'), 
                                                                                         day = _now.strftime('%d'))

# User Image path (end)

# User model (start)
# Update 6/27/2023 Asia/Manila

class User(models.Model):
    user_fname = models.CharField(max_length=200, verbose_name='First Name', blank=False)
    user_lname = models.CharField(max_length=200, verbose_name='Last Name', blank=False)
    user_email = models.EmailField(unique=True, max_length=200, verbose_name='Email', blank=False)
    user_position = models.CharField(max_length=200, verbose_name='Position', blank=False)

    user_image = models.ImageField(upload_to=image_path, default='profile_pic/image.jpg')

    def image_tag(self):
        return mark_safe('<img scr="/users/media/%s" width="50" height="50" />'%(self.user_image))

    date_added = models.DateTimeField(default=now)

    def __str__(self):
        return self.user_email
    
# User model (end)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField(default='null')
    body = models.TextField(default='null')
    created_on = models.DateTimeField(default=now)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']
    
    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

zds_systems/users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import User
from django.core.exceptions import ObjectDoesNotExist

def index(request):
    user_list = User.objects.order_by('-date_added')[:10]
    context = {'user_list': user_list}
    return render(request, 'userlist/index.html', context)

def add(request):
    return render(request, 'userlist/add.html')

def processadd(request):
    fname = request.POST.get('fname')
    lname = request.POST.get('lname')
    email = request.POST.get('email')
    position = request.POST.get('position')
    if request.FILES.get('image'):
        user_pic = request.FILES.get('image')
    else:
        user_pic = 'profile_pic/image.jpg'
    try: 
        n = User.objects.get(user_email=email)
        # n already exists
        return render(request, 'userlist/add.html', { 'error_message' : "Email " + email + " already existed " })
    except ObjectDoesNotExist:
        user = User.objects.create(user_email=email, user_fname=fname, user_lname=lname, user_position=position, user_image=user_pic)
        user.save()
        return HttpResponseRedirect('/users')
    
def detail(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        raise Http404("User does not exist")
    return render(request, 'userlist/detail.html', {'user': user})

zds_systems/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ZDS Systems | {% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
  </head>
  <body>

    <!-- Navbar -->
    {% include 'partials/_navbar.html' %}

    <div class="container">
        <div class="row mt-2">
            <div class="col-lg-12">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

zds_systems/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-dark mb-4">
    <div class="container">
      <a href="/users" class="navbar-brand">Users</a>
      <a href="add" class="navbar-brand">Add New</a>
      <a href="" class="navbar-brand">Login</a>
    </div>
  </nav>

zds_systems/templates/userlist/add.html
{% extends 'base.html' %}

{% block title %}
Add New User
{% endblock %}

{% block content %}

{% if error_message %}
<p class="alert alert-danger">
    <strong>
        {{ error_message }}
    </strong>
</p>
{% endif %}

<form action="{% url 'users:processadd' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}

    <div class="form-group">
        <label>First Name</label>
        <input type="text" name="fname" id="fname" class="form-control" required>
    </div>
    <div class="form-group">
        <label>Last Name</label>
        <input type="text" name="lname" id="lname" class="form-control" required>
    </div>
    <div class="form-group">
        <label>Email</label>
        <input type="email" name="email" id="email" class="form-control" required>
    </div>
    <div class="form-group">
        <label>Position</label>
        <input type="text" name="position" id="position" class="form-control" required>
    </div>
    <div class="form-group">
        <label>Profile Image</label>
        <input type="file" name="image" id="image" >
    </div>

    <button type="submit" class="btn btn-success mt-2">Add</button>

</form>

{% endblock %}

zds_systems/templates/userlist/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ user.user_fname }} {{ user.user_lname }}
{% endblock %}

{% block content %}
<h1> {{ user.user_fname }} {{ user.user_lname }} </h1>
<p class="text-muted">{{ user.user_email }}</p>
<p>Position: {{ user.user_position }}</p>
<div class="img-responsive text-center">
    <img src="">
</div>
{% endblock %}

zds_systems/templates/userlist/index.html
{% extends 'base.html' %}

{% block title %}
User List
{% endblock %}

{% block content %}
<h1 class="text-center mb-4">CRM User List</h1>
{% if user_list %}
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Position</th>
                <th>Profile Pic</th>
            </tr>
        </thead>
        <tbody>
            {% for user in user_list %} 
            <tr>
                <td>{{ user.user_fname }}</td>
                <td>{{ user.user_lname }}</td>
                <td>{{ user.user_email }}</td>
                <td>{{ user.user_position }}</td>
                <td>
                    <a href="{% url 'users:detail' user.id %}" class="">
                        <img src="image/{{ user.user_image }}" alt="user_image" width="50" class="rounded-circle">
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

{% endblock %}